# Generated by Django 5.2.1 on 2025-06-07 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BOS', 'Boston Celtics'), ('BRK', 'Brooklyn Nets'), ('CHA', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIL', 'Milwaukee Bucks'), ('MIN', 'Minnesota Timberwolves'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHX', 'Phoenix Suns'), ('POR', 'Portland Trail Blazers'), ('SAC', 'Sacramento Kings'), ('SAS', 'San Antonio Spurs'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards'), ('DET', 'Detroit Pistons')], max_length=3)),
                ('pts_vs_pg', models.FloatField(default=0.0)),
                ('pts_vs_sg', models.FloatField(default=0.0)),
                ('pts_vs_sf', models.FloatField(default=0.0)),
                ('pts_vs_pf', models.FloatField(default=0.0)),
                ('pts_vs_c', models.FloatField(default=0.0)),
                ('rebs_vs_pg', models.FloatField(default=0.0)),
                ('rebs_vs_sg', models.FloatField(default=0.0)),
                ('rebs_vs_sf', models.FloatField(default=0.0)),
                ('rebs_vs_pf', models.FloatField(default=0.0)),
                ('rebs_vs_c', models.FloatField(default=0.0)),
                ('asts_vs_pg', models.FloatField(default=0.0)),
                ('asts_vs_sg', models.FloatField(default=0.0)),
                ('asts_vs_sf', models.FloatField(default=0.0)),
                ('asts_vs_pf', models.FloatField(default=0.0)),
                ('asts_vs_c', models.FloatField(default=0.0)),
                ('stls_vs_pg', models.FloatField(default=0.0)),
                ('stls_vs_sg', models.FloatField(default=0.0)),
                ('stls_vs_sf', models.FloatField(default=0.0)),
                ('stls_vs_pf', models.FloatField(default=0.0)),
                ('stls_vs_c', models.FloatField(default=0.0)),
                ('blks_vs_pg', models.FloatField(default=0.0)),
                ('blks_vs_sg', models.FloatField(default=0.0)),
                ('blks_vs_sf', models.FloatField(default=0.0)),
                ('blks_vs_pf', models.FloatField(default=0.0)),
                ('blks_vs_c', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ptsAvg', models.FloatField(default=0.0)),
                ('rebsAvg', models.FloatField(default=0.0)),
                ('astsAvg', models.FloatField(default=0.0)),
                ('stlsAvg', models.FloatField(default=0.0)),
                ('blksAvg', models.FloatField(default=0.0)),
                ('ptsl10', models.FloatField(default=0.0)),
                ('rebsl10', models.FloatField(default=0.0)),
                ('astsl10', models.FloatField(default=0.0)),
                ('stlsl10', models.FloatField(default=0.0)),
                ('blksl10', models.FloatField(default=0.0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='locksmith_picks_app.team')),
            ],
        ),
    ]
