# Generated by Django 5.2.1 on 2025-06-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='astsAvg',
            new_name='apg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='astsl10',
            new_name='apg10',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='blksAvg',
            new_name='bpg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='blksl10',
            new_name='bpg10',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ptsAvg',
            new_name='ppg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ptsl10',
            new_name='ppg10',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='rebsAvg',
            new_name='rpg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='rebsl10',
            new_name='rpg10',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='stlsAvg',
            new_name='spg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='stlsl10',
            new_name='spg10',
        ),
    ]
