# Generated by Django 5.2.1 on 2025-06-17 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0003_mailinglistsubscriber_remove_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsubscriber',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locksmith_picks_app.team'),
        ),
    ]
