# Generated by Django 5.2.1 on 2025-06-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0004_alter_mailinglistsubscriber_favorite_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='asts_vs_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='asts_vs_pf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='asts_vs_pg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='asts_vs_sf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='asts_vs_sg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='blks_vs_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='blks_vs_pf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='blks_vs_pg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='blks_vs_sf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='blks_vs_sg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts_vs_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts_vs_pf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts_vs_pg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts_vs_sf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts_vs_sg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rebs_vs_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rebs_vs_pf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rebs_vs_pg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rebs_vs_sf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rebs_vs_sg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stls_vs_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stls_vs_pf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stls_vs_pg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stls_vs_sf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stls_vs_sg',
        ),
        migrations.CreateModel(
            name='DVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('points_allowed', models.FloatField(default=0.0)),
                ('rebounds_allowed', models.FloatField(default=0.0)),
                ('assists_allowed', models.FloatField(default=0.0)),
                ('steals_allowed', models.FloatField(default=0.0)),
                ('blocks_allowed', models.FloatField(default=0.0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvp', to='locksmith_picks_app.team')),
            ],
            options={
                'unique_together': {('team', 'position')},
            },
        ),
    ]
