# Generated by Django 5.2.1 on 2025-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0006_player_position_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
