# Generated by Django 5.2.1 on 2025-06-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0008_alter_team_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
