# Generated by Django 5.2.1 on 2025-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0010_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
