# Generated by Django 5.2.1 on 2025-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0011_player_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('G', 'Guard'), ('F', 'Forward'), ('C', 'Center'), ('G-F', 'Guard-Forward'), ('F-G', 'Forward-Guard'), ('F-C', 'Forward-Center'), ('C-F', 'Center-Forward')], max_length=4),
        ),
    ]
