# Generated by Django 5.2.1 on 2025-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmith_picks_app', '0013_player_ast_summary_player_blk_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvp',
            old_name='assists_allowed',
            new_name='assists_allowed_avg',
        ),
        migrations.RenameField(
            model_name='dvp',
            old_name='blocks_allowed',
            new_name='blocks_allowed_avg',
        ),
        migrations.RenameField(
            model_name='dvp',
            old_name='points_allowed',
            new_name='points_allowed_avg',
        ),
        migrations.RenameField(
            model_name='dvp',
            old_name='rebounds_allowed',
            new_name='rebounds_allowed_avg',
        ),
        migrations.RenameField(
            model_name='dvp',
            old_name='steals_allowed',
            new_name='steals_allowed_avg',
        ),
        migrations.AddField(
            model_name='dvp',
            name='assists_allowed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvp',
            name='blocks_allowed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvp',
            name='gameLogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvp',
            name='points_allowed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvp',
            name='rebounds_allowed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dvp',
            name='steals_allowed_total',
            field=models.IntegerField(default=0),
        ),
    ]
